name: kaizen_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  carousel_slider: ^4.1.1
  http: ^0.13.5
  google_fonts: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.10+1

flutter_native_splash:
  image: assets/images/kaizen_logo.png
  color: "#ffffff"


flutter:
  uses-material-design: true
  assets:
    - assets/images/



